### PR TITLE
Solving missing ID when truncate is false

### LINKED ISSUE #298: [CopyableText] missing id when not truncate
Use case example:
```
<CopyableText>test</Copyable>
```
output:
`Warning: Failed prop type: Please provide a valid ID for Text when truncate is active`

But in the docs saying that `id` just required when `truncate` is true, but in this case, `truncate` is using default value, that needs to be `false`

### PR DESCRIPTION
**Pull request by hamurabiaraujo**
Fixes #298 

Using `truncate` param instead of hard coded `truncate`

### CODE REVIEW

**Review by tiagoalvesdulce — CHANGES_REQUESTED** [review]
Thanks for this PR @hamurabiaraujo ! Can you change the default value of the `truncate` prop to true on `defaultProps` so we don't break unexpected stuff on politeiagui?

**Comment by hamurabiaraujo** [comment]
Off course!

**Comment by amassarwi** [comment]
Defaulting truncate to true will lead to the same console error we are trying to solve as we we won't have default ID ?

We may need to check pigui usage and set truncate to true explicitly.

**Comment by tiagoalvesdulce** [comment]
I don't get your point, `ids` are unique so having a default `id` doesn't make sense. `truncate` is just a boolean. If you are talking about setting `truncate` to true without defining an `id` we can make the id required when `truncate` is true.

**Comment by hamurabiaraujo** [comment]
Make sense to me what @amassarwi said. The error occour when the `ID` is not passed and the `truncate` is not set, because default is `null`, thus not required. If we force the default `truncate` to true, the error aways will appear because the id is not passed by default. 

We will solve the error from a side and get the same from other side.

**Comment by hamurabiaraujo** [comment]
Any decision about it? Should I do the changes requested?

**Comment by tiagoalvesdulce** [comment]
So, my final suggestion is to use the truncate prop and mark `id` as required if `truncate` is true. Here is an example of how to do that with `propTypes`:

```
handleDelete: function(props, propName, componentName) {
        if ((props['showDelete'] == true && (props[propName] == undefined || typeof(props[propName]) != 'function'))) {
            return new Error('Please provide a handleDelete function!');
        }
    },
```

But I still think the `truncate` value should be defaulted to true because it makes more sense for the component.

@amassarwi what do you think?

**Comment by amassarwi** [comment]
Sounds good to me, but as discussed on matrix this would require updating pigui to provide ids when needed
and to set truncate to false in other cases.

**Comment by victorgcramos** [comment]
Could you please rename the title of your PR to a more descriptive one?

**Comment by hamurabiaraujo** [comment]
The component uses something like a [default checker](https://github.com/decred/pi-ui/blob/master/src/utils.js#L23) for `truncate`  components. So, I just changed the default value for `truncate` to true.

**Review by tiagoalvesdulce — APPROVED** [review]

**Review by tiagoalvesdulce — APPROVED** [review]

**Pull request merged**
