### PR TITLE
Paginator component

### PR DESCRIPTION
**Pull request by bgptr**
This introduces a new Paginator component.  
Design-wise it follows: https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred---piui---decrediton?node-id=12%3A1024

This new component is used in https://github.com/decred/decrediton/pull/3603

paginator-piui

### CODE REVIEW

**Comment by amass01** [comment]
Thanks @bgptr, i think ideally we should use this component in https://github.com/decred/pi-ui/blob/master/src/components/Table/Table.jsx which has pagination already and looks like the design attached.

**Review by tiagoalvesdulce — COMMENTED** [review]
I agree we should use the `Paginator` component in the `Table` component.

There is a behavior I don't like in our current table pagination:

https://user-images.githubusercontent.com/13955303/143439681-3bd2103c-652a-4319-a67d-df72bda1ff00.mp4

See how it expands to the left? You did the same in your component but you're expanding to the right. Ideally the width of the component should be fixed for the same screen size. Like [MUI's React Pagination component](https://mui.com/components/pagination/).

https://user-images.githubusercontent.com/13955303/143440022-e969cabe-4f1e-4049-99d9-d964007a5413.mp4

Can you emulate this same behavior?

Other than that, your code looks good. You added an arrow icon but we already have `left` and `right` icons so I guess it's unnecessary. You also added the hexadecimal of colors we already have named, for example: `"paginator-arrow-color": "#2970FF"` should be: `"paginator-arrow-color": "var(--color-primary)"`.

To integrate your component on `Table`:

Table has basically 2 booleans and 2 functions responsible for dealing with pagination. They are: `canGoBack`, `canGoNext`,  `previousPage` and `nextPage`. The booleans are used to disable/enable left and right arrows and the functions are responsible to navigate through the pages. Should be pretty straight forward. Feel free to adapt the `Table` component if you must but I'd rather adapt the `Paginator` component to accept these props.

**Comment by bgptr** [comment]
@tiagoalvesdulce I've implemented your suggestions but left the arrow icon because the `left` and `right` icons are not the same as the ones in the design.

**Review by tiagoalvesdulce — COMMENTED** [review]
Cool. Will be removing the `left` and `right` arrows in a future PR. I see you are using `pixels` in the `Paginator` css. But we try to stick to `rems`. Any particular reason?

**Comment by bgptr** [comment]
No particular reason. I've replaced them.

**Review by tiagoalvesdulce — APPROVED** [review]
This PR LGTM. Only one more thing:

Can we remove the `user-select` here?
Screen Shot 2021-11-26 at 11 00 03

**Comment by bgptr** [comment]
Good catch. Removed it.+

**Pull request merged**
